# This is the configuration file for kitty terminal
# For more information, see https://sw.kovidgoyal.net/kitty/conf.html
# For your custom configurations, put it in ./kitty.conf
font_family FiraCode Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
# Keep Latin text in Fira Code while forcing CJK ranges to Source Han Sans.
symbol_map U+2E80-U+2EFF,U+2F00-U+2FDF,U+3000-U+303F,U+3040-U+30FF,U+3100-U+312F,U+31A0-U+31BF,U+31C0-U+31EF,U+3200-U+32FF,U+3300-U+33FF,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FE30-U+FE4F,U+FF00-U+FFEF Source Han Sans CN
enable_audio_bell no
font_size 12.0
window_padding_width 25
cursor_trail 1

# Themes can override any settings in this file
include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0
