color0 #1f1924
color1 #fd4663
color2 #ad67e4
color3 #5c72d6
color4 #cc6693
color5 #c593ec
color6 #96a5e9
color7 #f2f2f3
color8 #6e6277
color9 #fd4663
color10 #ad67e4
color11 #5c72d6
color12 #cc6693
color13 #c593ec
color14 #96a5e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1f1924
background            #1f1924
foreground            #f2f2f3
selection_foreground  #b3afb6
selection_background  #2a2230
active_border_color   #ad67e4
inactive_border_color #2a2230
url_color             #ad67e4

active_tab_foreground   #1f1825
active_tab_background   #ad67e4
inactive_tab_foreground #b3afb6
inactive_tab_background #2a2230
cursor_trail_color      #b3afb6
