color0 #181a25
color1 #fd4663
color2 #6778e4
color3 #855cd6
color4 #be66cc
color5 #939fec
color6 #b296e9
color7 #f2f2f3
color8 #626577
color9 #fd4663
color10 #6778e4
color11 #855cd6
color12 #be66cc
color13 #939fec
color14 #b296e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #181a25
background            #181a25
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #202331
active_border_color   #6778e4
inactive_border_color #202331
url_color             #6778e4

active_tab_foreground   #181a25
active_tab_background   #6778e4
inactive_tab_foreground #afb0b6
inactive_tab_background #202331
cursor_trail_color      #afb0b6
